/**
 * gen_law_cards.js
 * Downloads ChLaw.json.zip from law.moj.gov.tw, extracts it,
 * finds target laws, and generates a comprehensive TypeScript seed patch.
 */
const AdmZip = require('adm-zip');
const fs = require('fs');
const path = require('path');

// Target laws (name must match LawName in ChLaw.json)
const TARGET_LAWS = [
  '所得稅法',
  '所得基本稅額條例',
  '遺產及贈與稅法',
  '土地稅法',
  '房屋稅條例',
  '印花稅法',
  '加值型及非加值型營業稅法',
  '稅捐稽徵法',
  '商業會計法',
  '商業會計處理準則',
  '會計師法',
  '記帳士法',
  '商業登記法',
  '稅籍登記規則',
  '統一發票使用辦法',
  '各類所得扣繳率標準',
  '薪資所得扣繳辦法',
  '就業保險法',
  '洗錢防制法',
  '個人資料保護法',
  '行政程序法',
  '勞動基準法',
  '勞工保險條例',
  '全民健康保險法',
  '勞工退休金條例',
  '公司法',
];

// Law → category mapping
const LAW_CATEGORY = {
  '所得稅法': '所得稅',
  '所得基本稅額條例': '所得稅',
  '遺產及贈與稅法': '財產稅',
  '土地稅法': '財產稅',
  '房屋稅條例': '財產稅',
  '印花稅法': '財產稅',
  '加值型及非加值型營業稅法': '營業稅',
  '稅捐稽徵法': '稅務行政',
  '商業會計法': '會計',
  '商業會計處理準則': '會計',
  '會計師法': '職業法規',
  '記帳士法': '職業法規',
  '商業登記法': '商業登記',
  '稅籍登記規則': '稅務行政',
  '統一發票使用辦法': '稅務行政',
  '各類所得扣繳率標準': '扣繳',
  '薪資所得扣繳辦法': '扣繳',
  '就業保險法': '勞工保險',
  '洗錢防制法': '金融法規',
  '個人資料保護法': '隱私法規',
  '行政程序法': '行政法',
  '勞動基準法': '勞動法規',
  '勞工保險條例': '勞工保險',
  '全民健康保險法': '全民健保',
  '勞工退休金條例': '退休金',
  '公司法': '公司法規',
};

function extractKeywords(lawName, articleNo, content) {
  const tags = [lawName];
  const patterns = [
    /申報/g, /繳納/g, /免稅/g, /扣除/g, /罰則/g, /罰鍰/g,
    /停業/g, /廢止/g, /罰款/g, /補稅/g, /退稅/g, /課稅/g,
    /會計師/g, /記帳士/g, /稽徵/g, /稅率/g, /稅額/g,
    /保費/g, /投保/g, /給付/g, /退休/g, /資遣/g,
    /勞工/g, /雇主/g, /勞動契約/g,
  ];
  for (const p of patterns) {
    const key = p.source;
    if (p.test(content)) tags.push(key);
  }
  return [...new Set(tags)].slice(0, 6);
}

function buildTitle(articleNo, content) {
  // Take first clause up to first 、or 。or newline, max 30 chars
  const first = content.split(/[。\n]/)[0].replace(/\s+/g, ' ').trim();
  if (first.length <= 30) return `${articleNo} ${first}`;
  return `${articleNo} ${first.slice(0, 28)}…`;
}

// ── Main ──────────────────────────────────────────────────────────────────────
const zipPath = path.join(__dirname, '..', 'tmp_ChLaw.zip');
if (!fs.existsSync(zipPath)) {
  console.error('tmp_ChLaw.zip not found. Run the download first.');
  process.exit(1);
}

console.log('Extracting ZIP...');
const zip = new AdmZip(zipPath);
const entry = zip.getEntry('ChLaw.json');
if (!entry) {
  console.error('ChLaw.json not found in ZIP');
  process.exit(1);
}
let rawJson = entry.getData().toString('utf8');
if (rawJson.charCodeAt(0) === 0xFEFF) rawJson = rawJson.slice(1); // strip BOM
const parsed = JSON.parse(rawJson);
const json = parsed.Laws ?? parsed; // schema: { UpdateDate, Laws: [...] }
console.log(`Loaded ${json.length} laws from ChLaw.json`);

// Build a map for quick lookup
const lawMap = {};
for (const law of json) {
  if (TARGET_LAWS.includes(law.LawName)) {
    lawMap[law.LawName] = law;
  }
}
console.log('Found target laws:', Object.keys(lawMap).join(', '));

// Generate cards
let nextId = 2000; // start after existing max (1105)
const cards = [];

for (const lawName of TARGET_LAWS) {
  const law = lawMap[lawName];
  if (!law) {
    console.warn(`  ⚠  Not found in ChLaw.json: ${lawName}`);
    continue;
  }

  const category = LAW_CATEGORY[lawName] || lawName;
  let articleCount = 0;

  for (const article of law.LawArticles) {
    {
      if (article.ArticleType !== 'A') continue; // skip chapter headings
      // ArticleNo is already like "第 1 條" – normalise spacing
      const no = article.ArticleNo ? article.ArticleNo.replace(/\s+/g, '') : '';
      const content = (article.ArticleContent || '').replace(/\r\n/g, '\n').trim();
      if (!content || content.length < 5) continue;

      cards.push({
        cardId: nextId++,
        lawName,
        article: no,
        summary: buildTitle(no, content),
        content,
        category,
        searchKeywords: extractKeywords(lawName, no, content).join(' '),
        isActive: 1,
      });
      articleCount++;
    }}
  console.log(`  ${lawName}: ${articleCount} articles → ${articleCount} cards`);
}

console.log(`\nTotal new cards: ${cards.length} (IDs ${2000}–${nextId - 1})`);

// ── Emit TypeScript patch ──────────────────────────────────────────────────────
function escapeStr(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
}

const lines = [];
lines.push('// AUTO-GENERATED by scripts/gen_law_cards.js — DO NOT EDIT BY HAND');
lines.push('// Source: law.moj.gov.tw/api/Ch/Law/json');
lines.push(`// Generated: ${new Date().toISOString().slice(0, 10)}`);
lines.push('// Cards: ' + cards.length + ' (IDs 2000–' + (nextId - 1) + ')');
lines.push('');
lines.push('import type Database from \'better-sqlite3\';');
lines.push('');
lines.push('type LawCardSeed = {');
lines.push('  cardId: number;');
lines.push('  lawName: string;');
lines.push('  article?: string;');
lines.push('  summary?: string;');
lines.push('  content: string;');
lines.push('  category?: string;');
lines.push('  searchKeywords?: string;');
lines.push('  isActive?: number;');
lines.push('};');
lines.push('');
lines.push('export const mojLawCards: LawCardSeed[] = [');

for (const c of cards) {
  lines.push('  {');
  lines.push(`    cardId: ${c.cardId},`);
  lines.push(`    lawName: \`${escapeStr(c.lawName)}\`,`);
  lines.push(`    article: \`${escapeStr(c.article)}\`,`);
  lines.push(`    summary: \`${escapeStr(c.summary)}\`,`);
  lines.push(`    content: \`${escapeStr(c.content)}\`,`);
  lines.push(`    category: \`${escapeStr(c.category)}\`,`);
  lines.push(`    searchKeywords: \`${escapeStr(c.searchKeywords)}\`,`);
  lines.push(`    isActive: 1,`);
  lines.push('  },');
}
lines.push('];');
lines.push('');
lines.push('export function seedMojLawCards(db: Database.Database): void {');
lines.push('  const stmt = db.prepare(`');
lines.push('    INSERT OR REPLACE INTO law_cards');
lines.push('      (card_id, law_name, article, summary, content, category, search_keywords, is_active)');
lines.push('    VALUES');
lines.push('      (@cardId, @lawName, @article, @summary, @content, @category, @searchKeywords, @isActive)');
lines.push('  `);');
lines.push('  const run = db.transaction((cards: LawCardSeed[]) => {');
lines.push('    for (const c of cards) {');
lines.push('      stmt.run({');
lines.push('        cardId: c.cardId,');
lines.push('        lawName: c.lawName,');
lines.push('        article: c.article ?? null,');
lines.push('        summary: c.summary ?? null,');
lines.push('        content: c.content,');
lines.push('        category: c.category ?? null,');
lines.push('        searchKeywords: c.searchKeywords ?? null,');
lines.push('        isActive: c.isActive ?? 1,');
lines.push('      });');
lines.push('    }');
lines.push('  });');
lines.push('  run(mojLawCards);');
lines.push('');
lines.push('  // Deactivate old simplified cards for laws now covered comprehensively by MOJ data');
lines.push('  const coveredLaws = [...new Set(mojLawCards.map(c => c.lawName))];');
lines.push('  const deactivate = db.prepare(');
lines.push("    'UPDATE law_cards SET is_active = 0 WHERE law_name = ? AND card_id < 2000'");
lines.push('  );');
lines.push('  const deactivateAll = db.transaction(() => {');
lines.push('    for (const law of coveredLaws) deactivate.run(law);');
lines.push('  });');
lines.push('  deactivateAll();');
lines.push('}');

const outPath = path.join(__dirname, '..', 'src', 'main', 'db', 'seedMojLaws.ts');
fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`\nWrote ${outPath}`);
console.log('Next: import seedMojLawCards in seed.ts and call it from seedBaselineData()');
